#!/bin/bash

#Generated by command builder 0.1

timestamp="$(date +%s)"

ffmpeg \
\
-re -fflags +genpts -stream_loop -1 -i testclip.mp4 \
\
-flags +global_header -r 30000/1001 \
\
-pix_fmt yuv420p \
-c:v h264 \
-b:v:0 2000K -s:v:0 1280x720 \
\
-c:a:0 aac -ar 48000 -b:a:0 96k \
\
-map 0:v:0 -map 0:a:0 \
-g:v 30 -keyint_min:v 30 -sc_threshold:v 0 \
-color_primaries bt709 -color_trc bt709 -colorspace bt709 \
-tune zerolatency \
\
-adaptation_sets "id=0,seg_duration=2,streams=v id=1,seg_duration=2,streams=a" \
-frag_type every_frame -use_timeline 0 -streaming 1 -ldash 1 -window_size 3 \
-http_user_agent Akamai_Broadcaster_v1.0 -http_persistent 1 \
-media_seg_name "$timestamp"'/chunk-stream_$RepresentationID$-$Number%05d$.$ext$' \
-init_seg_name "$timestamp"'/init-stream$RepresentationID$.$ext$' \
-f dash \

# Add your entrypoint on the line above
